### local host test

GET http://localhost:3000/all_contacts


### BLACK MARKET

GET http://localhost:3000/black_market


### Hacker excersize

GET http://localhost:3000/dbaf78yh3n3r2rfwfnd8andfh?secret=nasdf82fe2

###

GET http://localhost:3000/api/dbaf78yh3n3r2rfwfnd8andfh?secret=nasdf82fe2


###

POST http://localhost:3000/api/dbaf78qierwy8bqyh3nnd8andfh
Content-Type: application/json

{
  "keyword": "budapest"
}

###

DELETE http://localhost:3000/api/dbaf78yh3nnd32438andfh